### ISSUE TITLE
Option "create API client with custom host, port" not working

### ISSUE THREAD

**Issue by Ra1nbowNeko** [mix1009/sdwebuiapi#1]
While using the default host and port, this project could work properly. 
But option "create API client with custom host, port" could not work.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/102323427/205486752-ac50281a-dfb8-4ed8-be4b-4daf6b4b7534.png">

It still point at the default port.

**Comment by mix1009** [comment]
Please check your code. Are you reinitializing the api again without the port argument?

**Comment by Ra1nbowNeko** [comment]
There is no problem with the configuration of my sdwebui server.

Here is another code for testing, and it could work well.

```python
import requests

url = "http://127.0.0.1:12799"

payload = {
    "prompt": "masterpiece",
    "negative_prompt": "nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet",
    "steps": 32,
    "width": 512,
    "height": 768
}

response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)
```

And here is the code which could not work.

```python
import webuiapi

# create API client with custom host, port
api = webuiapi.WebUIApi(host='127.0.0.1', port=12799)

# create API client with default sampler, steps.
api = webuiapi.WebUIApi(sampler='Euler a', steps=20)

result1 = api.txt2img(prompt="cute squirrel",
                    negative_prompt="ugly, out of frame",
                    seed=1003,
                    styles=["anime"],
                    cfg_scale=7,
#                      sampler_index='DDIM',
#                      steps=30,
                    )
```

And, according to the debugging information, it seems that the parameters "host" and "port" could not pass in.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/102323427/205644119-d20aded7-29b8-42c2-aab6-fc4adc8f866f.png">

**Comment by mix1009** [comment]
You reinitialized the api again without the port. 
Below code should work:
```
api = webuiapi.WebUIApi(host='127.0.0.1', port=12799, sampler='Euler a', steps=20)

result1 = api.txt2img(prompt="cute squirrel",
                    negative_prompt="ugly, out of frame",
                    seed=1003,
                    styles=["anime"],
                    cfg_scale=7,
                    )

```

**Comment by Ra1nbowNeko** [comment]
Thanks, the code you gave me could work well.
