### ISSUE TITLE
ребят как добавить параметр nfsw? я вписываю его просто "nfsw": True но это никак не работает

### ISSUE THREAD

**Issue by Juranik** [mix1009/sdwebuiapi#124]
ребят как добавить параметр nfsw? я вписываю его просто "nfsw": True но это никак не работает прошу вас люди добрые помогите((

**Comment by Juranik** [comment]
как добавить другие параметры правильно??? Guys, how do I add an nfsw parameter? and in general, how to add all the other parameters there CFG SCALE, SAMPLES, Negative_prompt, seed, etc, please guys help

**Comment by Ping7123** [comment]
должно работать без всякий NSFW, бери прост stable diffusion, запускай, врубай какую нибудь модельку и генерь с помощью клиента. У меня генерит NSFW спокойно без указания всяких NSFW

**Comment by Juranik** [comment]
> должно работать без всякий NSFW, бери прост stable diffusion, запускай, врубай какую нибудь модельку и генерь с помощью клиента. У меня генерит NSFW спокойно без указания всяких NSFW

решил использовать просто библиотеку просто nsfw, ну и в общем, проблему решил, но спасибо в любом случае.
