### ISSUE TITLE
problem with using adetailer 

### ISSUE THREAD

**Issue by saltedfisssh** [mix1009/sdwebuiapi#152]
```
adetailer = webuiapi.ADetailer(ad_model='face_yolov8n.pt', ad_denoising_strength=0.6)
res = api.txt2img(
    # enable_hr=enable_hr,
    prompt=prompt,
    negative_prompt=negative_prompt,
    width=width,
    height=height,
    controlnet_units=[ip_adapter, openpose] if use_ip_adapter else [openpose],
    adetailer=[adetailer]
).image
```
The logic for generating images seems different from webui, leading to strange results.
![image](https://github.com/mix1009/sdwebuiapi/assets/55906118/90c9c5b9-6ef9-4688-b315-c3672680cef4)

**Comment by davidmartinrius** [comment]
Hi @saltedfisssh , do you mean that using the same seed, cfscale, steps you get a different image when applying adetailer?

**Comment by saltedfisssh** [comment]
When using adetailer, only the facial part is recognized, but it attempts to generate more parts besides the face.  Use the same parameters as webui.

**Comment by saltedfisssh** [comment]
Sorry, during the process of reproducing, I found out that this is an issue with Adetailer. Thank you for your help!

**Comment by davidmartinrius** [comment]
Great! Good to know it is not a problem of this api wrapper. Bad to know that Adetailer has this behaviour.. thanks for letting me know!
