### ISSUE TITLE
webuiapi.py There is an error

### ISSUE THREAD

**Issue by zdoek001** [mix1009/sdwebuiapi#157]
if control_mode == 0:
            self.control_mode = 'Balanced',
        elif control_mode == 1:
            self.control_mode = 'My prompt is more important'
        elif control_mode == 2:
            self.control_mode = 'ControlNet is more important'
        else:
            self.control_mode = control_mode
            
            Adding an extra ',' in 'Balanced' will result in recognition errors

**Comment by mix1009** [comment]
Thank you. I'll fix the bug.
