### ISSUE TITLE
control_mode of ControlNetUnit is array, rather than string

### ISSUE THREAD

**Issue by Zhangyangrui916** [mix1009/sdwebuiapi#158]
Today I noticed that the inpainting result of api is different from webui.
It turned out that when using controlnet, the type of control_mode is wrong (array rather than str)

first: 
the wireshark shows control_mode is an array
![wireshark](https://github.com/mix1009/sdwebuiapi/assets/80372329/0ad2c8c9-fc1f-4205-8afb-7b49257d95e7)

second:
forcing it to be 'Balanced' rather than ['Balanced']  solved the problem. Now api is almost the same with webui.
![image](https://github.com/mix1009/sdwebuiapi/assets/80372329/23dde0fe-7c4b-49da-924d-8568ea8a0c25)

why ['Balanced']  would deteriate the influence of controlnet but do not throw error remains question

**Comment by mix1009** [comment]
Could you test with the new version 0.9.10 
There was a bug in 0.9.9 related to "Balanced" mode.
Thank you.

**Comment by Zhangyangrui916** [comment]
test OK。
I tried to fix it too, but never thought that a little comma will make it a tuple。 Good job
