### ISSUE TITLE
Any support for not using a preprocessor in controlnet?

### ISSUE THREAD

**Issue by Piper8x7b** [mix1009/sdwebuiapi#159]
I have a precomputed normal map im trying to use with the api's controlnet.
But I don't see an option to disable the preprocessor.
Is this not supported?

**Comment by Theroniya** [comment]
Simply ControlNetUnit(... module="none" ...). As "none" is the default, you can omit the module parameter.

**Comment by Piper8x7b** [comment]
Thanks!
