### ISSUE TITLE
The default initial_noise_multiplier leads to blurry image when using img2img

### ISSUE THREAD

**Issue by FlyHighest** [mix1009/sdwebuiapi#16]
Currently, the default value for  initial_noise_multiplier is 0, which will cause the generated image blurry. 

I think it's better to set default value as 1, to be consistent with stable-diffusion-webui default settings.

**Comment by mix1009** [comment]
Thank you.

Where did you find the default settings?

**Comment by FlyHighest** [comment]
It's in the webui opts:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8/modules/shared.py#L406

**Comment by FlyHighest** [comment]
Done.
