### ISSUE TITLE
width / height not working in img2img controlnet?

### ISSUE THREAD

**Issue by notintricate** [mix1009/sdwebuiapi#17]
Thanks for your work! Not sure if I'm doing something wrong, but I can't get anything but 512x512 as an output, despite I explicitly set 'width' : 768, 'height' : 768, (or any other values). Any hint is appreciated!

**Comment by mix1009** [comment]
Looks like it's working...

<img width="974" alt="controlnet_768" src="https://user-images.githubusercontent.com/1288793/221700298-b1f2ea29-45d9-4cfc-9aba-0cf3ce971730.png">

**Comment by notintricate** [comment]
Thanks for the feedback! 
Found the issue. I'm using controlnet+inpainting and  the `inpaint_full_res: bool = True` forced the output to be limited by the mask resolution. Setting it to `False` outputs desired dimensions.
