### ISSUE TITLE
Wrong payload for rembg

### ISSUE THREAD

**Issue by KonradBreitsprecher** [mix1009/sdwebuiapi#172]
Hello @mix1009,

using rembg failed with:
`RuntimeError: (500, '{"error":"HTTPException","detail":"Invalid encoded image","body":"","errors":""}')`

The error is an invalid payload at https://github.com/mix1009/sdwebuiapi/blob/main/webuiapi/webuiapi.py#L1283 with a wrong key for the image. Its `input_image`, not just `image` at least in 1.9.4 (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/feee37d75f1b168768014e4634dcb156ee649c05).

Otherwise works great!

**Comment by mix1009** [comment]
Thank you for the bug report. I've fixed in recent update.
image is renamed to input_image.
