### ISSUE TITLE
seed resize from width or Height and HiRes steps seems missing

### ISSUE THREAD

**Issue by MushroomFleet** [mix1009/sdwebuiapi#19]
tried to use:

#        hr_second_pass_steps = 8,        
#        seed_resize_from_h = 512,
#        seed_resize_from_w = 512,

but API says they do not exist, but they are listed?
If there is a list of the correct syntax please direct me, otherwise maybe a problem?

thanks!

**Comment by scruffynerf** [comment]
When using Controlnet, to be clearer...

**Comment by mix1009** [comment]
Now you can call normal txt2img and img2img with controlnet_units param to use ControlNet.
It should now be possible to pass those parameters :)
