### ISSUE TITLE
Consider publishing to pypi?

### ISSUE THREAD

**Issue by narugo1992** [mix1009/sdwebuiapi#2]
This code is useful when batching process something about stable diffusion webui. 

So do you consider publishing this code to pypi for more developer to use this as dependency? If so, I can provide necessary support.

**Comment by mix1009** [comment]
Thank you for the suggestion. I never published a python package. I'll try it tomorrow :)

**Comment by burak-yilmaz** [comment]
Ciao peeps! I'm a bit unfamiliar with Python and, funny enough, I couldn't figure out how to properly import this webuiapi.py to my Jupyter. I get the following error when I attemp to run the cell. What should I do before running the Jupyter? :pray: this will be extremely useful in my project. Thank you @mix1009 mix1009
<img width="753" alt="Screenshot 2022-12-20 at 22 37 08" src="https://user-images.githubusercontent.com/19609445/208771680-fa6df61f-c7b7-44eb-a6a8-1f393cb272fe.png">

**Comment by mix1009** [comment]
I just published the package to pypi.
https://pypi.org/project/webuiapi/

now you can install with
```
pip install webuiapi
```

If you are in jupyter notebook:
```
!pip install webuiapi
```

If you have any problem using the python package, please report here.

Thank you.
