### ISSUE TITLE
wildcards support

### ISSUE THREAD

**Issue by s1dlx** [mix1009/sdwebuiapi#21]
Hello!

I'd like to use [wildcards](https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards) in api calls. 

In the webui these are used directly in prompts and rendered at [`process`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards/blob/6ed81ed1eaee9145b596ab6385c38ffd8ce7b13f/scripts/wildcards.py#L33) time. The prompt is changed and the image is generated. The rendered prompt shows at the end in the png metadata.

With sdwebuiapi I tried

```python
import webuiapi

api = webuiapi.WebUIApi()
result = api.txt2img(prompt="__mywildcard__",
                    negative_prompt="",
                    seed=123,
                    cfg_scale=7)

print(result.info)
print(result.parameters)
```

which prints

```
{'prompt': '__mywidlcard__', ...}
```

I guess there are two possibilities:
1) the wildcard wasn't replaced
2) the wildcard was replaced but it is not showing into `result.info` as that contain the prompt *before* `process` is being called

~~I'd say option 2 is the most likely, but I'd like to find a way of having the actual prompt back with the image~~

after some testing I'm afraid it's option 1. The wildcards is not replaced

**Comment by mix1009** [comment]
I believe the processing chain does not take into account extensions when API is called. Wildcards extension doesn't seem to have API support for now. Maybe it's possible with script_name parameter but I didn't have time to try it.

**Comment by mix1009** [comment]
I tried testing with script_name parameter. I think it's not possible to reference scripts in the extensions folder.

**Comment by s1dlx** [comment]
> I tried testing with script_name parameter. I think it's not possible to reference scripts in the extensions folder.

I see, thanks for trying. I'll open an issue on webui repository for adding this feature

**Comment by mix1009** [comment]
Now you can use alwayson_scripts argument to use wildcards extension.

```
r = api.txt2img(prompt='photo of a cute girl __juice__',
                seed=1000,
                alwayson_scripts={"Simple wildcards":[]} # wildcards extension doesn't accept more parameters.
               )
r.image
```
