### ISSUE TITLE
May I suggest to use dicts as the input param for all functions?

### ISSUE THREAD

**Issue by zhouyi531** [mix1009/sdwebuiapi#23]
I would like to suggest that all input parameters in the function/method be changed to a dictionary. This would allow me to create a dictionary with key-value pairs that need to be overridden and benefit from the update() method to quickly override default values without affecting other defaults. This approach would make the code more flexible and extensible, and would also make it easier to read and understand the meaning of each parameter. Additionally, using a dictionary for input parameters would allow for named parameters, which is a more flexible way of passing arguments to a function or method. I believe this change would greatly improve the usability and maintainability of the code. Thank you for considering my suggestion.

**Comment by mix1009** [comment]
I don't want to have breaking api changes.

You can use ** to unpack dictionary to arguments:
```
d = {"prompt": "photo of a pretty girl",
     "height":768, "seed":1001}

r = api.txt2img(**d)
r.image
```

**Comment by zhouyi531** [comment]
Sure, thanks for your reply!
