### ISSUE TITLE
how to add lora

### ISSUE THREAD

**Issue by yier2333** [mix1009/sdwebuiapi#28]

**Comment by mix1009** [comment]
You can use the <lora:.....> inside your prompt. I'm getting the same result as webui.

```
r = api.txt2img(prompt='photo of a cute girl with black hair <lora:Moxin_10:0.6> shuimobysim',
                seed=102, eta=1.0)
r.image
```

**Comment by PandaXu313** [comment]
> 
The lora doesn't work when I'm using the same prompt as in webui

**Comment by jovijovi** [comment]
I found this [[Bug]: Skipping unknown extra network: lora #9274](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9274)

**Comment by PandaXu313** [comment]
> I found this [[Bug]: Skipping unknown extra network: lora #9274](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9274)

I used the solution in the [7984](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7984) and It works

**Comment by mix1009** [comment]
If webui is run with --nowebui . extra networks is not initialized. This is a webui bug.

It should work when launched with --api (without --nowebui).
