### ISSUE TITLE
The API does not work with HTTPS

### ISSUE THREAD

**Issue by barshag** [mix1009/sdwebuiapi#3]
Here is the code:
```
import webuiapi

# create API client
#api = webuiapi.WebUIApi()

# create API client with custom host, port
api = webuiapi.WebUIApi(host='XXX', port="443")

# create API client with default sampler, steps.
#api = webuiapi.WebUIApi(sampler='Euler a', steps=20)

result1 = api.txt2img(prompt="Panter screaming",
                    negative_prompt="ugly, out of frame",
                    seed=1003,
                    styles=["anime"],
                    cfg_scale=7,
#                      sampler_index='DDIM',
#                      steps=30,
                    )```



Here is the error:

```
to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (400, '<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n')

```

**Comment by mix1009** [comment]
Updated the library to add use_https option:
```
api = webuiapi.WebUIApi(host='XXX', port=443, use_https=True)
```

You could also set baseurl:
```
api = webuiapi.WebUIApi(baseurl='https://XXX:443/sdapi/v1')
```

Thank you for the bug report.
