### ISSUE TITLE
Error in img2img with ControlNets 

### ISSUE THREAD

**Issue by Stevada** [mix1009/sdwebuiapi#30]
Hi there, thank you for creating this extremely helpful API! I got the following error when I try to use img2img with ContronlNets. Could anyone help me out? 

> INFO:     127.0.0.1:36702 - "POST /controlnet/img2img HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 94, in receive
>     return self.receive_nowait()
>   File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 89, in receive_nowait
>     raise WouldBlock
> anyio.WouldBlock
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 77, in call_next
>     message = await recv_stream.receive()
>   File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 114, in receive
>     raise EndOfStream
> anyio.EndOfStream
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 271, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 125, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 104, in __call__
>     response = await self.dispatch_func(request, call_next)
>   File "/content/stable-diffusion-webui/modules/api/api.py", line 96, in log_and_time
>     res: Response = await call_next(req)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 80, in call_next
>     raise app_exc
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 69, in coro
>     await self.app(scope, receive_or_disconnect, send_no_error)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
>     await responder(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
>     await self.app(scope, receive, self.send_with_gzip)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 66, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 237, in app
>     raw_response = await run_endpoint_function(
>   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 165, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
>     return await anyio.to_thread.run_sync(func, *args)
>   File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 117, in controlnet_img2img
>     return self.controlnet_any2img(
>   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 127, in controlnet_any2img
>     script_runner = create_cn_script_runner(script_runner, any2img_request.controlnet_units, is_img2img)
>   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 186, in create_cn_script_runner
>     cn_script_args = [None] * cn_script.args_from
> TypeError: can't multiply sequence by non-int of type 'NoneType'

FYI, here is my code
```
img = Image.open("result.jpg")
unit1 = webuiapi.ControlNetUnit(input_image=img, module='canny', model='control_canny-fp16 [e3fe7712]')
unit2 = webuiapi.ControlNetUnit(input_image=img, module='depth', model='control_depth-fp16 [400750f6]', weight=0.5)

r2 = api.img2img(prompt="photo of a beautiful cat",
            images=[img], 
            width=512,
            height=512,
            controlnet_units=[unit1],
            sampler_name="Euler a",
            cfg_scale=7,
           )
```

Any idea is appreciated!!

**Comment by mix1009** [comment]
I would resize the img before passing it to webui. Could be a memory problem.

```
img = Image.open("result.jpg").resize((512,512))
```

**Comment by sunnysaxena** [comment]
**I got this type of error**
raise RuntimeError(response.status_code, response.text)
RuntimeError: (404, '\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>No interface is running</title>\n</head>\n<style>\n    body{\n    font-family: \'Lato\', sans-serif;\n    color: #888;\n    text-align: center;\n    }\n    #main{\n        padding-top:30px\n    }\n</style>\n<body>\n\n<div id="main">\n    <a href="https://www.gradio.app" target="_blank"><img src="https://gradio.app/assets/gradio.svg" style="width:150px"></a>\n        \t\t<h2>No interface is running right now</h2>\n</div>\n\n</body>\n</html>\n')

**Comment by Stevada** [comment]
> I would resize the img before passing it to webui. Could be a memory problem.
> 
> ```
> img = Image.open("result.jpg").resize((512,512))
> ```

Thank you for replying. I just tried and the same error is still there.

**Comment by sunnysaxena** [comment]
**Here I tried to use img2img with two ContronlNets and it's working fine for me.**

```
import webuiapi
import json
import requests
import io
from app import url
from PIL import Image, PngImagePlugin
from datetime import datetime

current_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")

# create API client with custom host, port and https
api = webuiapi.WebUIApi(host='your_public_url_.gradio.live', port=443, use_https=True)

r = api.txt2img(prompt="photo of a beautiful girl with blonde hair", height=512, seed=100)
img = r.image
img = img.resize((512, 512))

unit1 = webuiapi.ControlNetUnit(input_image=img, module='canny', model='control_canny-fp16 [e3fe7712]')
unit2 = webuiapi.ControlNetUnit(input_image=img, module='depth', model='control_depth-fp16 [400750f6]', weight=0.5)

r2 = api.img2img(prompt="photo of a beautiful girl",
                 images=[img],
                 width=512,
                 height=512,
                 controlnet_units=[unit1, unit2],
                 sampler_name="Euler a",
                 cfg_scale=7,
                 )

r2.image.save(current_time + '_controlnet_depth_output.png')
```

Output:
![2023_03_16-09_25_37_AM_controlnet_depth_output](https://user-images.githubusercontent.com/11352227/225511250-b27e06ae-0c4d-448b-9f3e-671d5c6b9d83.png)

**Comment by Stevada** [comment]
> **Here I tried to use img2img with two ContronlNets and it's working fine for me.**
> 
> ```
> import webuiapi
> import json
> import requests
> import io
> from app import url
> from PIL import Image, PngImagePlugin
> from datetime import datetime
> 
> current_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")
> 
> # create API client with custom host, port and https
> api = webuiapi.WebUIApi(host='your_public_url_.gradio.live', port=443, use_https=True)
> 
> r = api.txt2img(prompt="photo of a beautiful girl with blonde hair", height=512, seed=100)
> img = r.image
> img = img.resize((512, 512))
> 
> unit1 = webuiapi.ControlNetUnit(input_image=img, module='canny', model='control_canny-fp16 [e3fe7712]')
> unit2 = webuiapi.ControlNetUnit(input_image=img, module='depth', model='control_depth-fp16 [400750f6]', weight=0.5)
> 
> r2 = api.img2img(prompt="photo of a beautiful girl",
>                  images=[img],
>                  width=512,
>                  height=512,
>                  controlnet_units=[unit1, unit2],
>                  sampler_name="Euler a",
>                  cfg_scale=7,
>                  )
> 
> r2.image.save(current_time + '_controlnet_depth_output.png')
> ```
> 
> Output: ![2023_03_16-09_25_37_AM_controlnet_depth_output](https://user-images.githubusercontent.com/11352227/225511250-b27e06ae-0c4d-448b-9f3e-671d5c6b9d83.png)

thank you! I tried it and it worked. Actually, my old code without resizing surprisingly works today. I run this in Google Colab and I guess it was something wrong with colab's memory management.
