### ISSUE TITLE
Control net update API

### ISSUE THREAD

**Issue by nguyenvuducthuy** [mix1009/sdwebuiapi#33]
Hi,
Currently I saw control net update API due to some change from SD recently. Are you have this warning from your end?

    [ControlNet] warning: using deprecated '/controlnet/img2img' route
    [ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead

**Comment by mix1009** [comment]
Thank you for the heads up. I'll try the ControlNet with alwayson_scripts and update the API if I succeed :)

**Comment by mix1009** [comment]
Updated!  You can call with the same controlnet_units and it will use alwayson_scripts internally.

You can also pass 'ControlNet' to alwayson_scripts:
```
from webuiapi import raw_b64_img
unit1 = webuiapi.ControlNetUnit(input_image=img, module='canny', model='control_canny-fp16 [e3fe7712]')

r = api.txt2img(prompt="photo of a beautiful girl",
                seed=1000,
                alwayson_scripts={
                  "ControlNet": {
                      'args': [unit1.to_dict()]
                  }
                }
               )
r.image
```

**Comment by nguyenvuducthuy** [comment]
Thanks for quick action, it's working

**Comment by yebing1976** [comment]
alwayson_scripts={
                  "ControlNet": {
                      'args': [unit1.to_dict()]
                  }
What if I need to use multiple ControlNet?
