### ISSUE TITLE
SSL Error when working with custom host 

### ISSUE THREAD

**Issue by zackzhuang1996** [mix1009/sdwebuiapi#35]
api = webuiapi.WebUIApi(host='https://xx.gradio.live', port=7860, use_https=True)

`api.img2img(images=[img1],
                                        mask_image=img2,
                                        inpainting_fill=1,
                                        prompt="sks man face, 4k, realistic, detailed, HDR, 64k",
                                        negative_prompt="nude, black and white, close up, cartoon, 3d, denim, (disfigured), (deformed), (poorly drawn), (extra limbs), blurry, boring, sketch, lackluster, signature, letters, watermark, low res, horrific, mutated, artifacts, bad art, gross, b&w, poor quality, low quality, cropped",
                                        seed=-1,
                                        steps=50,
                                        controlnet_units=[unit1, unit2],
                                        cfg_scale=5.0,
                                        inpaint_full_res=True,
                                        denoising_strength=0.7,
                                        restore_faces=True)`

Error 
requests.exceptions.SSLError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //-ecfa-4760.gradio.live:7860/sdapi/v1/img2img (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by see2run** [comment]
how u solve this?

**Comment by davidmartinrius** [comment]
Hi @see2run,

To solve this you need to remove the https:// and set the port 443, https default port...

So, replace this 
`api = webuiapi.WebUIApi(host='https://whatever.gradio.live/', port=7860, use_https=True)
`
to this

`api = webuiapi.WebUIApi(host='whatever.gradio.live/', port=443, use_https=True)
`
Best regards,

David Martin Rius
