### ISSUE TITLE
How to do txt2img controlnet?

### ISSUE THREAD

**Issue by barshag** [mix1009/sdwebuiapi#46]
In the tutorial there is an example only for img2img, but it quite limited to many usecases..

**Comment by mix1009** [comment]
There is sample in README.md . If you want to use multiple contronets, you'll have to set it from webui setttings and restart.

**Comment by Louis24** [comment]
> There is sample in README.md . If you want to use multiple contronets, you'll have to set it from webui setttings and restart.

i follow the instruction it works, but when I use own image for canny, I has no effect
