### ISSUE TITLE
how to disable control net

### ISSUE THREAD

**Issue by night3759** [mix1009/sdwebuiapi#49]
After I use control net to generate pictures, I cannot generate a picture without control net, even if I didnot put the "controlnet_units=[units]" in the text2img function. Is there any command to disable the control net after I use it.

**Comment by sienaiwun** [comment]
"controlnet_units=[]" ?

**Comment by night3759** [comment]
> "controlnet_units=[]" ?

I tried, but not useful. Then I set the payload["alwayson_scripts"]={}, it works

**Comment by night3759** [comment]
> You can check whether controlnet_units are used by watching the value inside the result's "parameters"

It seems to be saved in the payload after I call the txt2img function, so I set the payload["alwayson_scripts"]={}, then the controlnet is disabled. Is there any better way?

**Comment by foobarhe** [comment]
yes, met the same issue here. 

I think the following code has bug？ It should turn on alwayson_scripts only if the input params of alwayson_scripts is set with ControlNet. e.g. `alwayson_scripts["ControlNet"].` 

```

        if controlnet_units and len(controlnet_units)>0:
            payload["alwayson_scripts"]["ControlNet"] = {
                "args": [x.to_dict() for x in controlnet_units]
            }
```

**Comment by foobarhe** [comment]
> 

so far a better way might to set `use_deprecated_controlnet=true` to not use alwayson_scripts.

**Comment by mix1009** [comment]
There is a bug in webui api implementation. When controlnet  parameter is not passed it uses the last passed controlnet.
Recent webuiapi pass empty controlnets to workaround the problem.
