### ISSUE TITLE
Support  batch txt2img & dept2Img  (request)

### ISSUE THREAD

**Issue by barshag** [mix1009/sdwebuiapi#5]
Hi,

Few issues that I wish will be  support in this library (or are supported but are not document)

1) I see that batch img2img is working, but i wonder whether it is possible to conduct batch inference of images using TXT2IMG  (instead of query each one of them with api call which are not that  time efficient).

2) Applying Depth2Img with SD 2.1 to images

3)  Using  3-rd party extensions.

Thanks again for your support! awesome library!

**Comment by mix1009** [comment]
1. The library can only provide what's provided by the API.
4 inference APIs are direct copy of the tabs from the UI. txt2img, img2img, Extras-Single Image, Extras-Batch Process.

2. If you could use it from webui interface, it should be possible to use Depth2Img in API also.

3. Third party extension could provide APIs. But they have to be programmed manually by the author of the extension. I only found one extension that provides APIs. There is a custom_get and custom_post method that you could use to call custom API endpoints.

Thank you for the requests.

**Comment by jgarciapft** [comment]
Issue 1.: as @mix1009 says, the API supports the same functionalities as the tabs of the WebUI. For txt2img there's no such thing as batch inference, but I think what you are trying to accomplish can be done through one of the Scripts (X/Y Plot, Prompt matrix, Prompts from file or textbox)
![Screenshot 2023-01-17 145157](https://user-images.githubusercontent.com/34139454/212916594-73e0fd67-4a5f-4d7c-9276-0d920302b7d9.png)

I've just added support for scripts in this pr #7. Take a look at the new README section 'Scripts support' to get an example for the X/Y Plot script.

Hope this can be of help

**Comment by mix1009** [comment]
PR by @jgarciapft has been merged in main branch.

Thank you @jgarciapft .
