### ISSUE TITLE
How do I use the api switching model

### ISSUE THREAD

**Issue by s348268281** [mix1009/sdwebuiapi#56]
as the title, I can't find any relevant parameters

**Comment by mix1009** [comment]
* Utility methods
```
# save current model name
old_model = api.util_get_current_model()

# get list of available models
models = api.util_get_model_names()

# set model (use exact name)
api.util_set_model(models[0])

# set model (find closest match)
api.util_set_model('robodiffusion')
```

**Comment by s348268281** [comment]
> * Utility methods
> 
> ```
> # save current model name
> old_model = api.util_get_current_model()
> 
> # get list of available models
> models = api.util_get_model_names()
> 
> # set model (use exact name)
> api.util_set_model(models[0])
> 
> # set model (find closest match)
> api.util_set_model('robodiffusion')
> ```

Thank you very much. It's very useful for me
