### ISSUE TITLE
How to make a multi controlnet effective？

### ISSUE THREAD

**Issue by xiaosai666** [mix1009/sdwebuiapi#59]
I used this api.img2img(images=[self.cv2_to_pil(image)],
                                steps=steps,
                                mask_image=mask,
                                height=height, 
                                width=width,
                                mask_blur=mask_blur,
                                inpainting_fill=inpainting_fill,
                                prompt=prompt,
                                negative_prompt=negative_prompt, 
                                seed=seed,
                                cfg_scale=cfg_scale,
                                denoising_strength=denoising_strength,
                                controlnet_units=[pose_unit, depth_unit],
                                sampler_name=sampler)
but only pose_unit work. How can I fix it?

**Comment by mix1009** [comment]
Did you increase "Multi ControlNet" from Settings/ControlNet from webui?

**Comment by xiaosai666** [comment]
How can i increase "Multi ControlNet" from Settings/ControlNet from webui? I didn't see any function.

**Comment by xiaosai666** [comment]
Do you mean to set it in the UI before calling it in the API? Can it be set through the API?

**Comment by mix1009** [comment]
Yes set it and restart the webui, and make sure multiple control nets are available from the webui user interface.

It's not possible to change controlnet settings through API.

**Comment by xiaosai666** [comment]
Very Thx!
