### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by randompaga** [mix1009/sdwebuiapi#66]
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\gjghjk.py", line 9, in <module>
    result1 = api.txt2img(prompt="cute squirrel",
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\webuiapi\webuiapi.py", line 270, in txt2img
    return self._to_api_result(response)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\webuiapi\webuiapi.py", line 139, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, '{"error":"RuntimeError","detail":"","body":"","errors":"There is no current event loop in thread \'AnyIO worker thread\'."}')

How to solve this issue?

**Comment by Ariliyazxp** [comment]
I was able to run before, and today I also suddenly got this error

    387     payload["alwayson_scripts"]["ControlNet"] = {
    388         "args": [x.to_dict() for x in controlnet_units]
    389     }
    390 response = self.session.post(url=f'{self.baseurl}/img2img', json=payload)
--> 391 return self._to_api_result(response)

File C:\Windows\System32\AI黑科技\webuiapi\webuiapi.py:142, in WebUIApi._to_api_result(self, response)
    139 def _to_api_result(self, response):
    141     if response.status_code != 200:
--> 142         raise RuntimeError(response.status_code, response.text)
    144     r = response.json()
    145     images = []

RuntimeError: (404, '{"detail":"Not Found"}')

It was all good before，but now  is error

**Comment by mix1009** [comment]
Please check if --api arg is passed when starting webui. And please update to latest version of webui if it fixes the issue.
