### ISSUE TITLE
[feature request] Async support

### ISSUE THREAD

**Issue by mikurei** [mix1009/sdwebuiapi#67]
Hello,

I think it would be cool if there was a native implementation of async. The API client blocks the event loop and you have to spawn a new thread and manage all the stuff like queues, tasks, workers etc. Asynchronous client is much simpler and cleaner.

Thanks!

**Comment by mix1009** [comment]
just added Async API support for txt2img, img2img, extra_single_image, extra_batch_images api call.

use_async=True parameter. You need asyncio, aiohttp packages installed.

```
result = await api.txt2img(prompt="cute kitten",
                    seed=1001,
                    use_async=True
                    )
result.image
```

**Comment by mikurei** [comment]
Awesome, thank you!

Closing this issue as completed.

reference commit: 9825a44

**Comment by zhangdanfeng888** [comment]
SyntaxError: 'await' outside function. What is wrong?

**Comment by mikurei** [comment]
> SyntaxError: 'await' outside function. What is wrong?

Hi, make sure that you are `await`ing inside an asynchronous function:
```python3
async def foo():
    await bar()
```

**Comment by zhangdanfeng888** [comment]
Can you share your code about async support? Thanks a lot.

**Comment by zhangdanfeng888** [comment]
Please, please, please...

**Comment by mikurei** [comment]
You need to run your async code in context of asynchronous event loop. Whats your use case?

Simple example:
```python3
import asyncio
import webuiapi


async def main():
    api = webuiapi.WebUIApi(host='127.0.0.1', port=7860)
    # pause the `main()` until the txt2img is done
    result = await api.txt2img(prompt="cute kitten", use_async=True)
    # do something with the result
    ...


asyncio.run(main())
# essentially the same as
# loop = asyncio,get_event_loop()
# loop.run_until_complete(main())
```

**Comment by zhangdanfeng888** [comment]
Okay, I want to use api to show the progress of txt2img tasks. I will try it. Thanks so much!

**Comment by mikurei** [comment]
You can do the following:
```python3
task = asyncio.create_task(api.txt2img(prompt="cute kitten", use_async=True))

while not task.done():
    progress = api.get_progress()
    print(progress)
    asyncio.sleep(1)
```

Full code based on the previous example:
```
import asyncio
import webuiapi


async def main():
    api = webuiapi.WebUIApi(host='127.0.0.1', port=7860)
    task = asyncio.create_task(api.txt2img(prompt="cute kitten", use_async=True))

    while not task.done():
        progress = api.get_progress()
        print(progress)
        asyncio.sleep(1)


asyncio.run(main())
```

**Comment by zhangdanfeng888** [comment]
Okay, thanks so so so so so so so much~
