### ISSUE TITLE
How to add Controlnet Unit into my code which use the way about "alwayson_scripts"

### ISSUE THREAD

**Issue by LLLYF** [mix1009/sdwebuiapi#70]
Sry to bother you ! I want to add more controlnet units in my code which use SD api to finish img2img.How to do that? My code is use "alwayson_scripts"  too.

**Comment by mix1009** [comment]
You can use alwayson_scripts along with controlnet_units. webuiapi internally adds ControlNet to the alwayson_scripts by default. If you pass use_deprecated_controlnet=True, it will use old /controlnet/img2img api endpoint.
