### ISSUE TITLE
Suddenly not works

### ISSUE THREAD

**Issue by avatarstones** [mix1009/sdwebuiapi#71]
3 days ago everything was fine.
Today even I tried
api.get_sd_models()
the result is
{'detail': 'Not Found'}

If call api.txt2img()
the result is
RuntimeError: (404, '{"detail":"Not Found"}')

Can anyone help? Thanks!

**Comment by mc-marcocheng** [comment]
Have you forgotten to add `--api` when running webui?

**Comment by avatarstones** [comment]
> Have you forgotten to add `--api` when running webui?

Thanks for your reminding. I did add --api.
Later I restarted the server and it worked well again.
Thanks!

**Comment by KangChou** [comment]
![image](https://github.com/mix1009/sdwebuiapi/assets/36963108/ec1944fd-71c8-4c8a-b808-0a68dfc9617b)
