### ISSUE TITLE
is there any ways to use deforum

### ISSUE THREAD

**Issue by hadoizz** [mix1009/sdwebuiapi#72]
hey guys i am looking to use deforum api any thing can help ?

**Comment by mix1009** [comment]
There is no API for deforum.
I automated the process by creating the deforum json file using python with wiggle. 
Then used playwright to automate webui. (load json file, generate, wait, repeat)

**Comment by hadoizz** [comment]
do you have any document or source can help me many thanks mix1009

**Comment by hadoizz** [comment]
an one can guide i can pay for help

**Comment by mix1009** [comment]
My code is hardcoded and has other dependencies. (openai, spleeter and code for audio synchronization)
But here's the rough process:

1. from deforum save json file. (Sometimes json format changes, so you might need to start from here time to time)
2. read json file and overwrite prompts and translation_x (using wiggle) .... and save as a new json file.
3. read new json file from deforum and generate.

To automate reading json files and generation I use playwright to automate chrome. It reads a folder and load each json file and generate. I also run multiple times for each json file.

**Comment by hadoizz** [comment]
but this will not help for using it on app ?

**Comment by mix1009** [comment]
What do you mean by using it on app?

**Comment by hadoizz** [comment]
i need to get deforum to use it on website or app which generate something similar to kaiber.ai

**Comment by hadoizz** [comment]
do you know anyone i can hire to do it ? many thanks in advance

**Comment by mix1009** [comment]
Contact me at mix1009@gmail.com
