### ISSUE TITLE
Use Multi-ControlNet without restarting the WebUI

### ISSUE THREAD

**Issue by amanjain1397appy** [mix1009/sdwebuiapi#74]
I am trying to use 2 controlnets (by referencing you code) as follows:

```
# img2img with multiple ControlNets (used 1.0 but also supports 2.0)
unit1 = webuiapi.ControlNetUnit(input_image=img, module='canny', model='control_canny-fp16 [e3fe7712]')
unit2 = webuiapi.ControlNetUnit(input_image=img, module='depth', model='control_depth-fp16 [400750f6]', weight=0.5)

r2 = api.img2img(prompt="girl",
            images=[img], 
            width=512,
            height=512,
            controlnet_units=[unit1, unit2],
            sampler_name="Euler a",
            cfg_scale=7,
           )
```

However I am getting results from only one of these control nets. I found out that I have to change the multi-control net setting in the webui and then restart the service to make the changes effective. Is there any way I can do this via the api itself?  

I am using this [repo](https://github.com/camenduru/stable-diffusion-webui-docker) to host my webui service, and the container seems to crash when I change the multi-controlnet settings and restart the service.

**Comment by mix1009** [comment]
No. controlnet settings can not be set using the api AFAIK.

**Comment by mix1009** [comment]
Please reopen the issue if this is possible.
