### ISSUE TITLE
How to operate get_progress()

### ISSUE THREAD

**Issue by s348268281** [mix1009/sdwebuiapi#79]
When I want to know the drawing progress, I use get_progress()，But I want to add some customization to its results so that I know which drawing task is working, how do I do that

it`s result like: {'progress': 0.81, 'eta_relative': 3.8092549847967803, 'state': {'skipped': False, 'interrupted': False, 'job': '', 'job_count': 1, 'job_timestamp': '20230531020526', 'job_no': 0, 'sampling_step': 24, 'sampling_steps': 30}, 'current_image': None, 'textinfo': None}

i want to add like:{"taskid":"111111111", 'progress': 0.81, 'eta_relative': 3.8092549847967803, 'state': {'skipped': False, 'interrupted': False, 'job': '', 'job_count': 1, 'job_timestamp': '20230531020526', 'job_no': 0, 'sampling_step': 24, 'sampling_steps': 30}, 'current_image': None, 'textinfo': None}

**Comment by mix1009** [comment]
Here is what I would do:

```
import asyncio

ar = api.txt2img(prompt='photo of a cute kitten', use_async=True)

while not ar.done():
    result = api.get_progress()
    print(result['progress'])
    await asyncio.sleep(0.1)

r = await ar
r.image
```

If you really need something for task_id use job_timestamp instead. But you'll have to monitor the job_count throughly.
1. Monitor and wait until job_count is 0
2. Call txt2img/img2img api async
3. Monitor and wait until job_count becomes 1 and save ['state']['job_timestamp']
4. Monitor and wait until job_timestamp is changed to other value or job_count to 0.
