### ISSUE TITLE
Matching some StableDiffusionProcessingImg2Img args to the Webui Inpaint options

### ISSUE THREAD

**Issue by gameveloster** [mix1009/sdwebuiapi#8]
I see the a number of args available here for `StableDiffusionProcessingImg2Img` 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/48a15821de768fea76e66f26df83df3fddf18f4b/modules/processing.py#L884-L905

that are exposed by `WebUIApi.img2img`

https://github.com/mix1009/sdwebuiapi/blob/main/webuiapi/webuiapi.py#L153-L191

Which of these args do we use if we want to pass into `WebUIApi.img2img` to adjust the Inpaint options on the webui that are called

- Mask mode (eg. "Inpaint masked")
- Masked content (eg. "fill", or "latent nothing")
- Inpaint area (eg. "Only masked")
- Only masked padding, pixels (eg. `12`)

![image](https://user-images.githubusercontent.com/103383490/214494092-aa01a4b5-08fa-421c-bee8-556c69b94674.png)

**Comment by gameveloster** [comment]
Also, is `denoising_strength` field in the API the same scale as "Denoising strength" on the webui? Setting `denoising_strength=0.75` appears to give a result that is as if you used a very low denoising strength on the webui

**Comment by mix1009** [comment]
I'm not sure if it's a bug or not.
This library just calls the API.
But I can't fix what API(webui) returns.

I didn't check the source code for the API.
I referenced https://localhost:7860/docs for API parameters.

If you find any bugs in this library (not passing the right parameters to the API), I'll fix it.

**Comment by wllbll** [comment]
args inpainting_fill control the value of "Masked content" on Webui frontend page, and you can find all args you mentioned here https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/4afaaf8a020c1df457bcf7250cb1c7f609699fa7/modules/ui.py#L740
