### ISSUE TITLE
control_net api problem because unit max num

### ISSUE THREAD

**Issue by zhuangdx** [mix1009/sdwebuiapi#80]
control_net will error with other extensions because control_net  max num，It can get the num, and post same num to api.

    def controlnet_settings(self):
        r = self.custom_get("controlnet/settings")
        return r

In txt2img function

        ...
        if controlnet_units and len(controlnet_units) > 0:
            payload["alwayson_scripts"]["ControlNet"] = {
                "args": [x.to_dict() for x in controlnet_units]
            }
            for i in range(self.control_net_max_models_num - len(payload["alwayson_scripts"]["ControlNet"])):
                payload["alwayson_scripts"]["ControlNet"]["args"].append({})
        elif self.has_controlnet:
            # workaround : if not passed, webui will use previous args!
            payload["alwayson_scripts"]["ControlNet"] = {"args": [{} for i in range(self.control_net_max_models_num)]}
        ...

**Comment by mix1009** [comment]
I think if we pass {"args": []} , webui will not use ControlNet.

Are you sure, previous controlnet is used when args is empty for that controlnet slot?

**Comment by zhuangdx** [comment]
yes, you are right. It not necessarily when empty.
