### ISSUE TITLE
/sdapi/v1/png-info needs the original encoded image

### ISSUE THREAD

**Issue by Theroniya** [mix1009/sdwebuiapi#81]
Apparently the necessary information gets lost when I convert the image for png_info() to Pil.Image and back.

Quick&Dirty I patched _to_api_result().  Kept the raw image and passed it unchanged to png-info. With that everything works fine.

**Comment by mix1009** [comment]
fixed in 0.9.3. Now the base64 encoding includes metadata from the original image.

Thank you for the report!
