### ISSUE TITLE
How can I achieve it like in webui: Always print all generation info to standard output

### ISSUE THREAD

**Issue by tcflying** [mix1009/sdwebuiapi#82]
return the detailed generatio information or in console, thanks

**Comment by Theroniya** [comment]
Do you mean prompt... Negative prompt: ... Steps: ... Sampler: ... ?

The encoded images contain this information. You get the text with /sdapi/v1/png-info. So you can print it to stdout.

Unfortunately sdwebuiapi.png_info() does not work. But you can find a working example for /sdapi/v1/png-info on https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by tcflying** [comment]
> 

thanks a lot, got it.

**Comment by mix1009** [comment]
you can print r.image.info and r.info (there is some info embedded in the image),
But when you re-encode the image with base64, the embedded info is not converted (why? I don't know).
The example from the page does not decode and re-encode base64, it just sends the received base64-encoded image.
